#!/usr/bin/env python3
"""Monitor for new devices/clients on the network.

The dd-wrt-based network router is queried for known DHCP clients using 
    $ ssh root@<ROUTER_IP> cat /tmp/dnsmasq.leases
and any new clients are identified and a notification is sent.  
Setup requirements:
    ssh access to the router must be enabled (ssh-keygen, ssh-copy-id).
"""

__version__ = "v0.2.2 200527"


#==========================================================
#
#  Chris Nelson, January 2019-2020
#
# 200527 v0.2.2 Bug fix for single line lookup_MAC response losing last letter.
# 200526 v0.2.1 Bug fix for finding not just first new device on an update run.
# 200522 v0.2  Track host name changes, support single quotes in notes, support older subprocess.checkoutput()
# 200426 v0.1  New
#
# Changes pending
#   
#==========================================================

import argparse
import subprocess
import sys
import re
import time
import collections
import mysql.connector
import requests
import logging
from funcs3 import setuplogging, loadconfig, getcfg, snd_notif

# Configs / Constants
# See config.cfg for DB params

py_version = float(sys.version_info.major) + float(sys.version_info.minor)/10

setuplogging(logfile= 'log.txt')
loadconfig  (cfgfile='config.cfg')


def main():

    # Check for database access and populate if non-existing
    db_connection = mysql.connector.connect(host=getcfg("DB_HOST"), user=getcfg("DB_USER"), passwd=getcfg("DB_PASS"))
    db_cursor = db_connection.cursor()
    db_cursor.execute("SHOW DATABASES")
    found = False
    for db in db_cursor:
        if getcfg("DB_DB") in db[0]:
            found = True
            break
    if not found:
        print(f"ERROR:  Manually create the <{getcfg('DB_DB')}> database.")
        sys.exit(1)

    db_connection = mysql.connector.connect(database=getcfg("DB_DB"), host=getcfg("DB_HOST"), user=getcfg("DB_USER"), passwd=getcfg("DB_PASS"))
    db_cursor = db_connection.cursor(buffered=True, dictionary=True)
    db_cursor.execute("SHOW TABLES")
    found = False
    for row in db_cursor:
        if getcfg('DB_TABLE') in row['Tables_in_' + getcfg('DB_DB')]:
            found = True
            break


    print(lookup_MAC(args.MAC))
    exit()


    if found and args.create_db:
        db_cursor.execute(f"DROP TABLE {getcfg('DB_TABLE')}")
        db_connection.commit()

    def db_add_client(MAC, record):
        cmd = "INSERT INTO {} (MAC, MACOUI, hostname, notes, first_seen, IP, expiry) VALUES (\'{}\', \'{}\', \'{}\', \'{}\', \'{}\', \'{}\', \'{}\')".format(
            getcfg('DB_TABLE'),
            MAC,
            lookup_MAC(MAC),
            record['hostname'],
            "-",
            time.asctime(time.localtime()),
            record['IP'],
            record['expiry'])
        db_cursor.execute(cmd)

    if not found or args.create_db:
        router_clients = get_router_clients()
        db_fields = "MAC VARCHAR(17), hostname VARCHAR(25), notes VARCHAR(50), first_seen VARCHAR(24), expiry VARCHAR(24), IP VARCHAR(15), MACOUI VARCHAR(30)"
        db_cursor.execute(f"CREATE TABLE {getcfg('DB_TABLE')} ({db_fields})")

        for MAC in router_clients:
            db_add_client (MAC, router_clients[MAC])
        db_connection.commit()


    # List known clients from database
    if args.list_db:
        get_database_clients(dump=True)
        sys.exit()


    # Add a note for a client to the database
    if args.add_note is not None:
        if args.MAC is None:
            print ("ERROR - Must specify the --MAC when using --add-note")
            sys.exit(1)
        db_cursor.execute(f"SELECT * FROM {getcfg('DB_TABLE')} WHERE MAC = '{args.MAC}'")
        if db_cursor.rowcount > 0:
            new_note = args.add_note.replace("'", "''")   # single quotes need to be doubled up in SQL
            db_cursor.execute(f"UPDATE {getcfg('DB_TABLE')} SET notes = '{new_note}' WHERE MAC = '{args.MAC}'")
            db_connection.commit()
        else:
            print (f"MAC address <{args.MAC}> not found in the database.")
            sys.exit(1)
        sys.exit()


    # Delete a client from the database
    if args.delete:
        if args.MAC is None:
            print ("ERROR - Must specify the --MAC when using --delete")
            sys.exit(1)
        db_cursor.execute(f"SELECT * FROM {getcfg('DB_TABLE')} WHERE MAC = '{args.MAC}'")
        if db_cursor.rowcount > 0:
            db_cursor.execute(f"DELETE FROM {getcfg('DB_TABLE')} WHERE MAC = '{args.MAC}'")
            db_connection.commit()
        else:
            print (f"MAC address <{args.MAC}> not found in the database.")
            sys.exit(1)
        sys.exit()


    # Update database from router
    if args.update:
        router_clients = get_router_clients()
        database_clients = get_database_clients()
        for MAC in router_clients:
            if MAC not in database_clients:
                msg = f"\n{router_clients[MAC]['hostname']}\n{router_clients[MAC]['IP']}\n{MAC}\n{lookup_MAC(MAC)}"
                snd_notif (subj="New LAN client found", msg=msg, log=True)
                db_add_client (MAC, router_clients[MAC])
                continue
            if router_clients[MAC]['hostname'] != database_clients[MAC]['hostname']:
                msg = (f"{MAC} / {database_clients[MAC]['hostname']:<20} New hostname: {router_clients[MAC]['hostname']}")
                logging.info(msg)
                db_cursor.execute(f"UPDATE {getcfg('DB_TABLE')} SET hostname = \'{router_clients[MAC]['hostname']}\' WHERE MAC = '{MAC}'")
            if router_clients[MAC]['IP'] != database_clients[MAC]['IP']:
                msg = (f"{MAC} / {database_clients[MAC]['hostname']:<20} New IP:       {router_clients[MAC]['IP']}")
                logging.info(msg)
                db_cursor.execute(f"UPDATE {getcfg('DB_TABLE')} SET IP = \'{router_clients[MAC]['IP']}\' WHERE MAC = '{MAC}'")
            if router_clients[MAC]['expiry'] != database_clients[MAC]['expiry']:
                msg = (f"{MAC} / {database_clients[MAC]['hostname']:<20} New expiry:   {router_clients[MAC]['expiry']}")
                logging.info(msg)
                db_cursor.execute(f"UPDATE {getcfg('DB_TABLE')} SET expiry = \'{router_clients[MAC]['expiry']}\' WHERE MAC = '{MAC}'")

        db_connection.commit()
        sys.exit()


    # List known clients from router
    if args.list_router:
        get_router_clients(dump=True)
        sys.exit()


def get_database_clients(dump=False):
    """ Get clients currently in the database, return a sorted dictionary of dictionaries, keyed by MAC
        {
            MAC:  { hostname:, IP:, expiry:, first_seen:, notes: }
        }
    """
    db_connection = mysql.connector.connect(database=getcfg("DB_DB"), host=getcfg("DB_HOST"), user=getcfg("DB_USER"), passwd=getcfg("DB_PASS"))
    db_cursor = db_connection.cursor(buffered=True, dictionary=True)
    db_cursor.execute(f"SELECT * FROM {getcfg('DB_TABLE')}")
    clients_list = {}
    for row in db_cursor:
        clients_list[row['MAC']] = {
            "hostname":   row['hostname'],
            "IP":         row['IP'],
            "expiry":     row['expiry'],
            "first_seen": row['first_seen'],
            "notes":      row['notes'],
            "MACOUI":     row['MACOUI'] }
    clients_list = collections.OrderedDict(sorted(clients_list.items()))

    if dump:
        print(f"{'Hostname':<25}  {'First seen':<24}  {'Current IP':<13}  {'IP Expiry':<24}  {'MAC':<17}  {'MAC Org Unique ID':<30}  {'Notes'}")
        for MAC in clients_list:
            print("{:<25}  {:<24}  {:<13}  {:<24}  {:<17}  {:<30}  {}".format(
                clients_list[MAC]['hostname'],
                clients_list[MAC]['first_seen'],
                clients_list[MAC]['IP'],
                clients_list[MAC]['expiry'],
                MAC,
                clients_list[MAC]['MACOUI'],
                clients_list[MAC]['notes']))
        print (f"  <{db_cursor.rowcount}>  known clients.")

    return clients_list


def get_router_clients(dump=False):
    """ Get leases from the router, return a sorted dictionary of dictionaries, keyed by MAC
        {
            MAC:  { hostname:, IP:, expiry: }
        }
    """
    clients_list = {}
    try:
        _cmd = ["ssh", "root@" + getcfg("ROUTER_IP"), "cat", getcfg("ROUTER_DHCP")]
        if py_version >= 3.7:
            clients = subprocess.run(_cmd, capture_output=True, text=True).stdout.split("\n")
        else:   #Py 3.6 .run does not support capture_output, so use the old method.
            clients = subprocess.run(_cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True).stdout.split("\n")
    except Exception as e:
        print("Exception <{}>".format(e))
    # 1587457675 00:0d:c5:5c:82:6d 192.168.1.105 Hopper-ETH0 01:00:0d:c5:5c:82:6d
    line_re = re.compile(r"([\d]+) ([\dabcdef:]+) ([\d.]+) ([\S]+)") # [\dabcdef:]+")
    for line in clients:
        xx = line_re.match(line)
        if xx:
            if xx.group(1) == '0':
                expiry = "static lease"
            else:
                expiry = time.asctime(time.localtime(int(xx.group(1))))
            clients_list[xx.group(2)] = {"hostname":xx.group(4), "IP":xx.group(3), "expiry":expiry}
        else:
            if len(line) > 0:
                print ("ERROR in get_router_clients:  This line looks bogus:\n  ", line)
    clients_list = collections.OrderedDict(sorted(clients_list.items()))

    if dump:
        count = 0
        for client in clients_list:
            count += 1
            print("{:<25} {} {:<13}  {}".format(
                clients_list[client]["expiry"],
                client, 
                clients_list[client]["IP"],
                clients_list[client]["hostname"]))
        print (f"  <{count}>  known clients.")

    return clients_list


def lookup_MAC(MAC):
    r = requests.get("https://oidsearch.s.dd-wrt.com/search/" + MAC[0:8])
    if r.status_code == 200:
        _next = False
        for line in r.text.split("\n"):
            print (line)
            if _next:
                break
            if "<h2>" in line:
                _next = True
        if _next:
            if "<br>" in line:
                search_result = line[0:line.find("<br>")]
            else:
                search_result = line
            if search_result == "":
                search_result = "--none--"
    else:
        search_result = "OID search failed"

    return (search_result)



if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('-u', '--update', action="store_true",
                        help="Check the router for new connections and update database.")
    parser.add_argument('-l', '--list-db', action='store_true',
                        help="Print known clients on the network from the database.")
    parser.add_argument('--list-router', action='store_true',
                        help="Print known clients on the network from the router.")
    parser.add_argument('--create-db', action='store_true',
                        help="Create a fresh database and populate it with the current clients.")
    parser.add_argument('-a', '--add-note', type=str,
                        help="Add a note to the db for the specified --MAC.")
    parser.add_argument('--delete', action='store_true',
                        help="Delete from the db the specified --MAC.")
    parser.add_argument('-M', '--MAC', type=str,
                        help="MAC address in the database to be modified or deleted.")
    parser.add_argument('-V', '--version', action='version', version='%(prog)s ' + __version__,
                        help="Return version number and exit.")

    if len(sys.argv)==1:      # Useful for empty command line help
        parser.print_help()
        sys.exit()

    args = parser.parse_args()

    main()
    sys.exit()
